// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class SendMessageResponse;
@class SendMessageResponseBuilder;


typedef NS_ENUM(SInt32, Test) {
  TestTestId = 16,
};

BOOL TestIsValidValue(Test value);
NSString *NSStringFromTest(Test value);

typedef NS_ENUM(SInt32, MessageCmdId) {
  MessageCmdIdCmdidC2SMessageData = 256,
  MessageCmdIdCmdidS2CMessageData = 257,
  MessageCmdIdCmdidC2SMessageSend = 258,
  MessageCmdIdCmdidS2CMessageSend = 259,
  MessageCmdIdCmdidCpsMessageSend = 260,
  MessageCmdIdCmdidSpcMessageSend = 261,
};

BOOL MessageCmdIdIsValidValue(MessageCmdId value);
NSString *NSStringFromMessageCmdId(MessageCmdId value);

typedef NS_ENUM(SInt32, SendMessageResponseError) {
  SendMessageResponseErrorErrOk = 0,
  SendMessageResponseErrorErrSys = -1,
};

BOOL SendMessageResponseErrorIsValidValue(SendMessageResponseError value);
NSString *NSStringFromSendMessageResponseError(SendMessageResponseError value);


@interface MsgRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define SendMessageResponse_err_code @"errCode"
#define SendMessageResponse_err_msg @"errMsg"
#define SendMessageResponse_from @"pb_from"
#define SendMessageResponse_text @"text"
#define SendMessageResponse_topic @"topic"
@interface SendMessageResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasErrCode_:1;
  BOOL hasErrMsg_:1;
  BOOL hasFrom_:1;
  BOOL hasText_:1;
  BOOL hasTopic_:1;
  SInt32 errCode;
  NSString* errMsg;
  NSString* pb_from;
  NSString* text;
  NSString* topic;
}
- (BOOL) hasErrCode;
- (BOOL) hasErrMsg;
- (BOOL) hasFrom;
- (BOOL) hasText;
- (BOOL) hasTopic;
@property (readonly) SInt32 errCode;
@property (readonly, strong) NSString* errMsg;
@property (readonly, strong) NSString* pb_from;
@property (readonly, strong) NSString* text;
@property (readonly, strong) NSString* topic;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SendMessageResponseBuilder*) builder;
+ (SendMessageResponseBuilder*) builder;
+ (SendMessageResponseBuilder*) builderWithPrototype:(SendMessageResponse*) prototype;
- (SendMessageResponseBuilder*) toBuilder;

+ (SendMessageResponse*) parseFromData:(NSData*) data;
+ (SendMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendMessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SendMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SendMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SendMessageResponseBuilder : PBGeneratedMessageBuilder {
@private
  SendMessageResponse* resultSendMessageResponse;
}

- (SendMessageResponse*) defaultInstance;

- (SendMessageResponseBuilder*) clear;
- (SendMessageResponseBuilder*) clone;

- (SendMessageResponse*) build;
- (SendMessageResponse*) buildPartial;

- (SendMessageResponseBuilder*) mergeFrom:(SendMessageResponse*) other;
- (SendMessageResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SendMessageResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasErrCode;
- (SInt32) errCode;
- (SendMessageResponseBuilder*) setErrCode:(SInt32) value;
- (SendMessageResponseBuilder*) clearErrCode;

- (BOOL) hasErrMsg;
- (NSString*) errMsg;
- (SendMessageResponseBuilder*) setErrMsg:(NSString*) value;
- (SendMessageResponseBuilder*) clearErrMsg;

- (BOOL) hasFrom;
- (NSString*) pb_from;
- (SendMessageResponseBuilder*) setFrom:(NSString*) value;
- (SendMessageResponseBuilder*) clearFrom;

- (BOOL) hasText;
- (NSString*) text;
- (SendMessageResponseBuilder*) setText:(NSString*) value;
- (SendMessageResponseBuilder*) clearText;

- (BOOL) hasTopic;
- (NSString*) topic;
- (SendMessageResponseBuilder*) setTopic:(NSString*) value;
- (SendMessageResponseBuilder*) clearTopic;
@end


// @@protoc_insertion_point(global_scope)
