// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class HelloRequest;
@class HelloRequestBuilder;
@class HelloResponse;
@class HelloResponseBuilder;
@class create;
@class createBuilder;
@class create_ack;
@class create_ackBuilder;
@class login;
@class loginBuilder;
@class login_ack;
@class login_ackBuilder;



@interface WatchdogLoginRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define create_name @"name"
#define create_sex @"sex"
#define create_phone @"phone"
@interface create : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasName_:1;
  BOOL hasPhone_:1;
  BOOL hasSex_:1;
  NSString* name;
  NSString* phone;
  UInt32 sex;
}
- (BOOL) hasName;
- (BOOL) hasSex;
- (BOOL) hasPhone;
@property (readonly, strong) NSString* name;
@property (readonly) UInt32 sex;
@property (readonly, strong) NSString* phone;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (createBuilder*) builder;
+ (createBuilder*) builder;
+ (createBuilder*) builderWithPrototype:(create*) prototype;
- (createBuilder*) toBuilder;

+ (create*) parseFromData:(NSData*) data;
+ (create*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (create*) parseFromInputStream:(NSInputStream*) input;
+ (create*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (create*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (create*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface createBuilder : PBGeneratedMessageBuilder {
@private
  create* resultCreate;
}

- (create*) defaultInstance;

- (createBuilder*) clear;
- (createBuilder*) clone;

- (create*) build;
- (create*) buildPartial;

- (createBuilder*) mergeFrom:(create*) other;
- (createBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (createBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (createBuilder*) setName:(NSString*) value;
- (createBuilder*) clearName;

- (BOOL) hasSex;
- (UInt32) sex;
- (createBuilder*) setSex:(UInt32) value;
- (createBuilder*) clearSex;

- (BOOL) hasPhone;
- (NSString*) phone;
- (createBuilder*) setPhone:(NSString*) value;
- (createBuilder*) clearPhone;
@end

#define create_ack_pid @"pid"
#define create_ack_code @"code"
#define create_ack_code_msg @"codeMsg"
@interface create_ack : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPid_:1;
  BOOL hasCodeMsg_:1;
  BOOL hasCode_:1;
  NSString* pid;
  NSString* codeMsg;
  UInt32 code;
}
- (BOOL) hasPid;
- (BOOL) hasCode;
- (BOOL) hasCodeMsg;
@property (readonly, strong) NSString* pid;
@property (readonly) UInt32 code;
@property (readonly, strong) NSString* codeMsg;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (create_ackBuilder*) builder;
+ (create_ackBuilder*) builder;
+ (create_ackBuilder*) builderWithPrototype:(create_ack*) prototype;
- (create_ackBuilder*) toBuilder;

+ (create_ack*) parseFromData:(NSData*) data;
+ (create_ack*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (create_ack*) parseFromInputStream:(NSInputStream*) input;
+ (create_ack*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (create_ack*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (create_ack*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface create_ackBuilder : PBGeneratedMessageBuilder {
@private
  create_ack* resultCreateAck;
}

- (create_ack*) defaultInstance;

- (create_ackBuilder*) clear;
- (create_ackBuilder*) clone;

- (create_ack*) build;
- (create_ack*) buildPartial;

- (create_ackBuilder*) mergeFrom:(create_ack*) other;
- (create_ackBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (create_ackBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPid;
- (NSString*) pid;
- (create_ackBuilder*) setPid:(NSString*) value;
- (create_ackBuilder*) clearPid;

- (BOOL) hasCode;
- (UInt32) code;
- (create_ackBuilder*) setCode:(UInt32) value;
- (create_ackBuilder*) clearCode;

- (BOOL) hasCodeMsg;
- (NSString*) codeMsg;
- (create_ackBuilder*) setCodeMsg:(NSString*) value;
- (create_ackBuilder*) clearCodeMsg;
@end

#define login_pid @"pid"
#define login_secret @"secret"
@interface login : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPid_:1;
  BOOL hasSecret_:1;
  NSString* pid;
  NSString* secret;
}
- (BOOL) hasPid;
- (BOOL) hasSecret;
@property (readonly, strong) NSString* pid;
@property (readonly, strong) NSString* secret;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (loginBuilder*) builder;
+ (loginBuilder*) builder;
+ (loginBuilder*) builderWithPrototype:(login*) prototype;
- (loginBuilder*) toBuilder;

+ (login*) parseFromData:(NSData*) data;
+ (login*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (login*) parseFromInputStream:(NSInputStream*) input;
+ (login*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (login*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (login*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface loginBuilder : PBGeneratedMessageBuilder {
@private
  login* resultLogin;
}

- (login*) defaultInstance;

- (loginBuilder*) clear;
- (loginBuilder*) clone;

- (login*) build;
- (login*) buildPartial;

- (loginBuilder*) mergeFrom:(login*) other;
- (loginBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (loginBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPid;
- (NSString*) pid;
- (loginBuilder*) setPid:(NSString*) value;
- (loginBuilder*) clearPid;

- (BOOL) hasSecret;
- (NSString*) secret;
- (loginBuilder*) setSecret:(NSString*) value;
- (loginBuilder*) clearSecret;
@end

#define login_ack_code @"code"
#define login_ack_code_msg @"codeMsg"
@interface login_ack : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCodeMsg_:1;
  BOOL hasCode_:1;
  NSString* codeMsg;
  UInt32 code;
}
- (BOOL) hasCode;
- (BOOL) hasCodeMsg;
@property (readonly) UInt32 code;
@property (readonly, strong) NSString* codeMsg;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (login_ackBuilder*) builder;
+ (login_ackBuilder*) builder;
+ (login_ackBuilder*) builderWithPrototype:(login_ack*) prototype;
- (login_ackBuilder*) toBuilder;

+ (login_ack*) parseFromData:(NSData*) data;
+ (login_ack*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (login_ack*) parseFromInputStream:(NSInputStream*) input;
+ (login_ack*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (login_ack*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (login_ack*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface login_ackBuilder : PBGeneratedMessageBuilder {
@private
  login_ack* resultLoginAck;
}

- (login_ack*) defaultInstance;

- (login_ackBuilder*) clear;
- (login_ackBuilder*) clone;

- (login_ack*) build;
- (login_ack*) buildPartial;

- (login_ackBuilder*) mergeFrom:(login_ack*) other;
- (login_ackBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (login_ackBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCode;
- (UInt32) code;
- (login_ackBuilder*) setCode:(UInt32) value;
- (login_ackBuilder*) clearCode;

- (BOOL) hasCodeMsg;
- (NSString*) codeMsg;
- (login_ackBuilder*) setCodeMsg:(NSString*) value;
- (login_ackBuilder*) clearCodeMsg;
@end

#define HelloRequest_user @"user"
#define HelloRequest_text @"text"
@interface HelloRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUser_:1;
  BOOL hasText_:1;
  NSString* user;
  NSString* text;
}
- (BOOL) hasUser;
- (BOOL) hasText;
@property (readonly, strong) NSString* user;
@property (readonly, strong) NSString* text;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HelloRequestBuilder*) builder;
+ (HelloRequestBuilder*) builder;
+ (HelloRequestBuilder*) builderWithPrototype:(HelloRequest*) prototype;
- (HelloRequestBuilder*) toBuilder;

+ (HelloRequest*) parseFromData:(NSData*) data;
+ (HelloRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HelloRequest*) parseFromInputStream:(NSInputStream*) input;
+ (HelloRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HelloRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HelloRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HelloRequestBuilder : PBGeneratedMessageBuilder {
@private
  HelloRequest* resultHelloRequest;
}

- (HelloRequest*) defaultInstance;

- (HelloRequestBuilder*) clear;
- (HelloRequestBuilder*) clone;

- (HelloRequest*) build;
- (HelloRequest*) buildPartial;

- (HelloRequestBuilder*) mergeFrom:(HelloRequest*) other;
- (HelloRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HelloRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUser;
- (NSString*) user;
- (HelloRequestBuilder*) setUser:(NSString*) value;
- (HelloRequestBuilder*) clearUser;

- (BOOL) hasText;
- (NSString*) text;
- (HelloRequestBuilder*) setText:(NSString*) value;
- (HelloRequestBuilder*) clearText;
@end

#define HelloResponse_retcode @"retcode"
#define HelloResponse_errmsg @"errmsg"
@interface HelloResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRetcode_:1;
  BOOL hasErrmsg_:1;
  SInt32 retcode;
  NSString* errmsg;
}
- (BOOL) hasRetcode;
- (BOOL) hasErrmsg;
@property (readonly) SInt32 retcode;
@property (readonly, strong) NSString* errmsg;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HelloResponseBuilder*) builder;
+ (HelloResponseBuilder*) builder;
+ (HelloResponseBuilder*) builderWithPrototype:(HelloResponse*) prototype;
- (HelloResponseBuilder*) toBuilder;

+ (HelloResponse*) parseFromData:(NSData*) data;
+ (HelloResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HelloResponse*) parseFromInputStream:(NSInputStream*) input;
+ (HelloResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HelloResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HelloResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HelloResponseBuilder : PBGeneratedMessageBuilder {
@private
  HelloResponse* resultHelloResponse;
}

- (HelloResponse*) defaultInstance;

- (HelloResponseBuilder*) clear;
- (HelloResponseBuilder*) clone;

- (HelloResponse*) build;
- (HelloResponse*) buildPartial;

- (HelloResponseBuilder*) mergeFrom:(HelloResponse*) other;
- (HelloResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HelloResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRetcode;
- (SInt32) retcode;
- (HelloResponseBuilder*) setRetcode:(SInt32) value;
- (HelloResponseBuilder*) clearRetcode;

- (BOOL) hasErrmsg;
- (NSString*) errmsg;
- (HelloResponseBuilder*) setErrmsg:(NSString*) value;
- (HelloResponseBuilder*) clearErrmsg;
@end


// @@protoc_insertion_point(global_scope)
